<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>WaveLinkBackup.App</RootNamespace>
    <AssemblyName>WaveLinkBackup</AssemblyName>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../WaveLinkBackup.Core/WaveLinkBackup.Core.csproj" />
  </ItemGroup>

</Project>
